#!/usr/bin/env python3

import argparse
import socket
import ssl

DEFAULT_SERVER = "proj5.3700.network"
DEFAULT_PORT = 443

class Crawler:
    def __init__(self, args):
        self.server = args.server
        self.port = args.port
        self.username = args.username
        self.password = args.password

    def run(self):
        request = "GET / HTTP/1.1\r\nHost: {}\r\nUser-Agent: Crawler/1.0\r\nConnection: close\r\n\r\n".format(self.server)

        print("Request to %s:%d" % (self.server, self.port))
        print(request)
        new_socket = socket.create_connection((self.server, self.port))
        ssl_context = ssl.create_default_context()

        mysocket = ssl_context.wrap_socket(new_socket, server_hostname=self.server)
        mysocket.send(request.encode('ascii'))

        data = mysocket.recv(1000)
        print("Response:\n%s" % data.decode('ascii'))

        mysocket.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='crawl Fakebook')
    parser.add_argument('-s', dest="server", type=str, default=DEFAULT_SERVER, help="The server to crawl")
    parser.add_argument('-p', dest="port", type=int, default=DEFAULT_PORT, help="The port to use")
    parser.add_argument('username', type=str, help="The username to use")
    parser.add_argument('password', type=str, help="The password to use")
    args = parser.parse_args()
    sender = Crawler(args)
    sender.run()
